name: korlinks
description: "A new Flutter project."
publish_to: "none"
version: 1.0.3+50
environment:
  sdk: ^3.5.4

dependencies:
  alphabet_list_view: ^1.1.2
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.3.4
  firebase_performance: ^0.10.1
  flashy_tab_bar2: ^0.0.10
  flutter:
    sdk: flutter
  flutter_contacts: ^1.1.9+2
  get: ^4.7.2
  in_app_update: ^4.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  icons_plus: ^5.0.0
  path: ^1.9.0
  vcard_vcf: ^0.1.5
  permission_handler: ^11.3.1
  share_plus: ^10.1.3
  shimmer: ^3.0.0
  url_launcher: ^6.3.1
  file_picker:
  connectivity_plus: ^7.0.0
  csv: ^6.0.0

dev_dependencies:
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
